---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
  namespace: web-apps
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGFpd3drOXI0
  CLOUDINARY_KEY: NTE2NzI4MzQxMTg1Mzkx
  CLOUDINARY_SECRET: V0N0WUtlZXNXTEVoeGxfU0oycWRoTkdtb2Jr
  MAPBOX_TOKEN: cGsuZXlKMUlqb2liWFZvWVcxdFlXUnRhV3hvWVc1a1pYWnZjSE1pTENKaElqb2lZMjFuYjI5alozVjRNWGRsTXpKcWMyZDVjM0ozYlRCMFppSjkuSlBjNG5BT1R1UGw2aG8zaHNkM05GQQ==
  DB_URL: bW9uZ29kYitzcnY6Ly9tdWhhbW1hZG1pbGhhbmRldm9wc19kYl91c2VyOlFFTlVXSUpDZUUzWWpvdVVAbXVoYW1tYWRtaWxoYW5kZXZvcHMueHhjbmVvby5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9bXVoYW1tYWRtaWxoYW5kZXZvcHM=
  SECRET: bXVoYW1tYWRtaWxoYW5kZXZvcHM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
  namespace: web-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: muhammadmilhandevops/camp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 45
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 45

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
  namespace: web-apps
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
